export const ROMAN_NUMBERALS = {
    M: 1000,
    CM: 900,
    D: 500,
    CD: 400,
    C: 100,
    XC: 90,
    L: 50,
    XL: 40,
    X: 10,
    IX: 9,
    V: 5,
    IV: 4,
    I: 1
};

export const CONVERSIONS = {
    LITRES_GALLONS: 4.546,
    KILOMETER_MILE: 1.609,
    ACRE_HECTARE: 2.471,
    GRAM_OUNCE: 28.35,
    GRAM_STONE: 6350,
    GRAM_POUND: 453.6, 
}

export const INITAL_FORMATS = {
    FIRST_INITIAL__LAST_INITIAL: 'fl',
    FIRST_NAME__LAST_INITIAL: 'Fl',
    FIRST_INITIAL__LAST_NAME: 'fL',
    FIRST_INITIAL__MIDDLE_INITIALS__LAST_NAME: 'fmL',
    FIRST_INITIAL__MIDDLE_INITIALS__LAST_INITIAL: 'fml',
    FIRST_NAME__MIDDLE_INITIALS__LAST_NAME: 'FmL'
}